- name: Pull image from repository
  docker_image:
    name: immah/yolo-backend:latest
    source: pull

- name: Create Node.js Backend Container
  docker_container:
    name: immah-yolo-backend
    image: immah/yolo-backend:latest
    networks:
      - name: app-net
    ports:
      - "5000:5000"
    command: "npm start"
    restart_policy: unless-stopped
  become: yes